# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/Instruction_Memory_ip/Instruction_Memory_ip.xci
# IP: The module: 'Instruction_Memory_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/Instruction_Memory_ip/Instruction_Memory_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Memory_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/Instruction_Memory_ip/Instruction_Memory_ip.xci
# IP: The module: 'Instruction_Memory_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/Instruction_Memory_ip/Instruction_Memory_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Memory_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
