# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip.xci
# IP: The module: 'CPU_Main_Clock_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip.xci
# IP: The module: 'CPU_Main_Clock_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Cyphe/Documents/SUSTech Assignment/Term 4/Computer Organization/Project/project_1.srcs/sources_1/ip/CPU_Main_Clock_ip/CPU_Main_Clock_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Main_Clock_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
